<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\PaymentLog;
use Illuminate\Http\Request;
use Midtrans\Config;
use Midtrans\Snap;
use Illuminate\Support\Facades\Http;

class UserController extends Controller
{
    public function index(Request $request)
    {
        $query = User::query();

        if ($request->filled('search')) {
            $query->where('name', 'like', '%' . $request->search . '%')
                  ->orWhere('email', 'like', '%' . $request->search . '%');
        }

        if ($request->filled('status')) {
            if ($request->status === 'premium') {
                $query->where('subscription', 'premium')
                      ->where('subscription_ends_at', '>', now());
            } elseif ($request->status === 'expired') {
                $query->where('subscription', 'premium')
                      ->where('subscription_ends_at', '<=', now());
            } elseif ($request->status === 'free') {
                $query->where('subscription', 'free');
            }
        }

        $users = $query->orderBy('created_at', 'desc')->paginate(15);

        return view('admin.users.index', compact('users'));
    }

    public function show($id)
    {
        $user = User::with('paymentLogs')->findOrFail($id);
        return view('admin.users.show', compact('user'));
    }

    public function updateSubscription(Request $request, $id)
    {
        $user = User::findOrFail($id);
        
        $request->validate([
            'subscription' => 'required|in:free,premium',
            'subscription_ends_at' => 'nullable|date',
        ]);

        $user->subscription = $request->subscription;
        if ($request->subscription === 'premium' && $request->filled('subscription_ends_at')) {
            $user->subscription_ends_at = $request->subscription_ends_at;
        } elseif ($request->subscription === 'free') {
            $user->subscription_ends_at = null;
        }
        $user->save();

        return back()->with('success', 'Status langganan user berhasil diupdate secara manual.');
    }

    public function destroy($id)
    {
        $user = User::findOrFail($id);
        if ($user->id === auth()->id() || $user->role === 'admin') {
            return back()->with('error', 'Tidak dapat menghapus akun admin!');
        }
        
        $user->delete();
        return redirect()->route('admin.users.index')->with('success', 'User berhasil dihapus.');
    }

    // Generate new payment for user manually from admin
    public function createPayment(Request $request, $id)
    {
        $user = User::findOrFail($id);
        
        Config::$serverKey    = config('midtrans.server_key');
        Config::$clientKey    = config('midtrans.client_key');
        Config::$isProduction = config('midtrans.is_production', false);
        Config::$isSanitized  = true;
        Config::$is3ds        = true;

        $orderId = "ORDER-" . time() . "-" . $user->id;
        $amount = 49000;

        $params = [
            'transaction_details' => [
                'order_id' => $orderId,
                'gross_amount' => $amount,
            ],
            'customer_details' => [
                'first_name' => $user->name,
                'email' => $user->email,
                'phone' => $user->no_telepon ?? '',
            ],
        ];

        try {
            $snapToken = Snap::getSnapToken($params);
            
            // Simpan log awal
            PaymentLog::create([
                'user_id' => $user->id,
                'order_id' => $orderId,
                'snap_token' => $snapToken,
                'gross_amount' => $amount,
                'status' => 'pending',
                'notes' => 'Generated by Admin',
            ]);

            return back()->with('success', "Link pembayaran (Snap Token) berhasil dibuat. Order ID: $orderId");
        } catch (\Exception $e) {
            return back()->with('error', 'Gagal membuat pembayaran: ' . $e->getMessage());
        }
    }

    // Cek status manual ke Midtrans API (Backup jika webhook gagal)
    public function checkStatus($id)
    {
        $paymentLog = PaymentLog::findOrFail($id);
        
        $serverKey = config('midtrans.server_key');
        $baseUrl = config('midtrans.is_production') ? 'https://api.midtrans.com/v2' : 'https://api.sandbox.midtrans.com/v2';
        
        try {
            $response = Http::withBasicAuth($serverKey, '')
                            ->get("{$baseUrl}/{$paymentLog->order_id}/status");
            
            if ($response->successful()) {
                $result = $response->json();
                $status = $result['transaction_status'] ?? $paymentLog->status;
                
                // Update log
                $paymentLog->status = $status;
                $paymentLog->payment_type = $result['payment_type'] ?? $paymentLog->payment_type;
                $paymentLog->transaction_id = $result['transaction_id'] ?? $paymentLog->transaction_id;
                $paymentLog->raw_response = $result;
                
                if (isset($result['va_numbers']) && count($result['va_numbers']) > 0) {
                    $paymentLog->bank = $result['va_numbers'][0]['bank'] ?? null;
                    $paymentLog->va_number = $result['va_numbers'][0]['va_number'] ?? null;
                }

                if ($status == 'settlement' || $status == 'capture') {
                    $paymentLog->paid_at = now();
                    $paymentLog->save();
                    
                    // Update user subscription
                    $user = $paymentLog->user;
                    $user->subscription = 'premium';
                    if ($user->subscription_ends_at && \Carbon\Carbon::parse($user->subscription_ends_at)->isFuture()) {
                        $user->subscription_ends_at = \Carbon\Carbon::parse($user->subscription_ends_at)->addYear();
                    } else {
                        $user->subscription_ends_at = now()->addYear();
                    }
                    $user->save();
                    
                    return back()->with('success', "Status berhasil diupdate ke Berhasil/Settlement. Langganan User otomatis aktif.");
                }

                $paymentLog->save();
                return back()->with('success', "Status berhasil disinkronisasi: " . ucfirst($status));
            } else {
                return back()->with('error', 'Gagal mengecek status ke Midtrans. Mungkin transaksi belum pernah dibayar (belum tercatat di Midtrans API).');
            }
        } catch (\Exception $e) {
            return back()->with('error', 'Error Midtrans API: ' . $e->getMessage());
        }
    }
}
